DD-150: Make sure existing DOI of migrated dataset is used as PID and DataCite is not contacted
DANS-KNAW/dd-dans-deposit-to-dataverse pull request #9
Opened 2020-10-06 10:18 UTC by vesaakerman

Fixes DD-150:

* tells Dataverse to keep the `DANS DOI` as `PID`, instead of minting a new one 

Where should the reviewer @DANS-KNAW/dataversedans start?

Related pull requests on github
repo                       | PR                | note
-------------------------- | ----------------- | ----
easy-                      | [PR#](PRlink)     | ..

2020-10-06 14:15 UTC, janvanmansum requested changes
How did you test this? Each and every time I have tried this it results in an exception. Also, note that not every dataset that comes in will have an exsiting DOI.

2020-10-13 12:00 UTC, vesaakerman commented on src/main/assembly/dist/cfg/application.properties
> +dataverse.api-key=16ca2257-b7d6-4268-b0e9-e6436671a97c
yep, that came by accident in the PR

2020-10-13 12:19 UTC, vesaakerman commented
How did I test this? I did it by running run-service.sh for `dd-dans-deposit-to-dataverse` and for `easy-validate-dans-bag`.
And then I placed a bag in `data/inbox` in `dd-dans-deposit-to-dataverse`.
But, to be honest, I also didn't get it that far that the bag was published (I committed the code as it was before taking days off, and forgot to inform that it was not all clear yet. Sorry about that).
Dataverse checks that the DOI is accessible.  I first got error messages concerning non-valid DOIs.  I replaced the DOI in the test data with an existing DOI, and then I got the error message that you probably also got:
` Server returned: status line: 'HTTP/1.1 500 Internal Server Error', body: '{"status":"ERROR","message":"Command edu.harvard.iq.dataverse.engine.command.impl.PublishDatasetCommand@1f1cf254 failed: Exception thrown from bean: javax.ejb.EJBException: Transaction aborted"}'`
So, when publishing the dataset something goes wrong.  Perhaps you or someone else might have clues on this?

Also, I didn't know that not all datasets have a DOI.  I mean datasets that are imported using dd-dans-deposit-to-dataverse.
We should then call `createDataset` method instead of `importDataset` method if the `DOI` is not found?

2020-10-20 09:05 UTC, janvanmansum approved these changes

2020-10-20 09:09 UTC, merged